// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/billtrust/meetup-terraform-provider/api-client/models"
)

// NewCreateMascotParams creates a new CreateMascotParams object
// with the default values initialized.
func NewCreateMascotParams() *CreateMascotParams {
	var ()
	return &CreateMascotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMascotParamsWithTimeout creates a new CreateMascotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateMascotParamsWithTimeout(timeout time.Duration) *CreateMascotParams {
	var ()
	return &CreateMascotParams{

		timeout: timeout,
	}
}

// NewCreateMascotParamsWithContext creates a new CreateMascotParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateMascotParamsWithContext(ctx context.Context) *CreateMascotParams {
	var ()
	return &CreateMascotParams{

		Context: ctx,
	}
}

// NewCreateMascotParamsWithHTTPClient creates a new CreateMascotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateMascotParamsWithHTTPClient(client *http.Client) *CreateMascotParams {
	var ()
	return &CreateMascotParams{
		HTTPClient: client,
	}
}

/*CreateMascotParams contains all the parameters to send to the API endpoint
for the create mascot operation typically these are written to a http.Request
*/
type CreateMascotParams struct {

	/*CreateRequest*/
	CreateRequest *models.CreateMascotRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create mascot params
func (o *CreateMascotParams) WithTimeout(timeout time.Duration) *CreateMascotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create mascot params
func (o *CreateMascotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create mascot params
func (o *CreateMascotParams) WithContext(ctx context.Context) *CreateMascotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create mascot params
func (o *CreateMascotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create mascot params
func (o *CreateMascotParams) WithHTTPClient(client *http.Client) *CreateMascotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create mascot params
func (o *CreateMascotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateRequest adds the createRequest to the create mascot params
func (o *CreateMascotParams) WithCreateRequest(createRequest *models.CreateMascotRequest) *CreateMascotParams {
	o.SetCreateRequest(createRequest)
	return o
}

// SetCreateRequest adds the createRequest to the create mascot params
func (o *CreateMascotParams) SetCreateRequest(createRequest *models.CreateMascotRequest) {
	o.CreateRequest = createRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMascotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateRequest != nil {
		if err := r.SetBodyParam(o.CreateRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
