// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/billtrust/meetup-terraform-provider/api-client/models"
)

// CreateMascotReader is a Reader for the CreateMascot structure.
type CreateMascotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMascotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateMascotCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateMascotCreated creates a CreateMascotCreated with default headers values
func NewCreateMascotCreated() *CreateMascotCreated {
	return &CreateMascotCreated{}
}

/*CreateMascotCreated handles this case with default header values.

The new mascot
*/
type CreateMascotCreated struct {
	Payload *models.MascotResponse
}

func (o *CreateMascotCreated) Error() string {
	return fmt.Sprintf("[POST /][%d] createMascotCreated  %+v", 201, o.Payload)
}

func (o *CreateMascotCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MascotResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
