// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteMascotParams creates a new DeleteMascotParams object
// with the default values initialized.
func NewDeleteMascotParams() *DeleteMascotParams {
	var ()
	return &DeleteMascotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMascotParamsWithTimeout creates a new DeleteMascotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMascotParamsWithTimeout(timeout time.Duration) *DeleteMascotParams {
	var ()
	return &DeleteMascotParams{

		timeout: timeout,
	}
}

// NewDeleteMascotParamsWithContext creates a new DeleteMascotParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMascotParamsWithContext(ctx context.Context) *DeleteMascotParams {
	var ()
	return &DeleteMascotParams{

		Context: ctx,
	}
}

// NewDeleteMascotParamsWithHTTPClient creates a new DeleteMascotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMascotParamsWithHTTPClient(client *http.Client) *DeleteMascotParams {
	var ()
	return &DeleteMascotParams{
		HTTPClient: client,
	}
}

/*DeleteMascotParams contains all the parameters to send to the API endpoint
for the delete mascot operation typically these are written to a http.Request
*/
type DeleteMascotParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete mascot params
func (o *DeleteMascotParams) WithTimeout(timeout time.Duration) *DeleteMascotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete mascot params
func (o *DeleteMascotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete mascot params
func (o *DeleteMascotParams) WithContext(ctx context.Context) *DeleteMascotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete mascot params
func (o *DeleteMascotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete mascot params
func (o *DeleteMascotParams) WithHTTPClient(client *http.Client) *DeleteMascotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete mascot params
func (o *DeleteMascotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete mascot params
func (o *DeleteMascotParams) WithID(id string) *DeleteMascotParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete mascot params
func (o *DeleteMascotParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMascotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
