// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteMascotReader is a Reader for the DeleteMascot structure.
type DeleteMascotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMascotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteMascotNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteMascotNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteMascotNoContent creates a DeleteMascotNoContent with default headers values
func NewDeleteMascotNoContent() *DeleteMascotNoContent {
	return &DeleteMascotNoContent{}
}

/*DeleteMascotNoContent handles this case with default header values.

Success
*/
type DeleteMascotNoContent struct {
}

func (o *DeleteMascotNoContent) Error() string {
	return fmt.Sprintf("[DELETE /{id}][%d] deleteMascotNoContent ", 204)
}

func (o *DeleteMascotNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMascotNotFound creates a DeleteMascotNotFound with default headers values
func NewDeleteMascotNotFound() *DeleteMascotNotFound {
	return &DeleteMascotNotFound{}
}

/*DeleteMascotNotFound handles this case with default header values.

Not Found
*/
type DeleteMascotNotFound struct {
}

func (o *DeleteMascotNotFound) Error() string {
	return fmt.Sprintf("[DELETE /{id}][%d] deleteMascotNotFound ", 404)
}

func (o *DeleteMascotNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
