// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateMascot creates a mascot
*/
func (a *Client) CreateMascot(params *CreateMascotParams) (*CreateMascotCreated, error) {
	// TODO: Validate the params before sending
	fmt.Println("AAAAAHHHH")
	if params == nil {
		params = NewCreateMascotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateMascot",
		Method:             "POST",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateMascotReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateMascotCreated), nil

}

/*
DeleteMascot deletes a mascot
*/
func (a *Client) DeleteMascot(params *DeleteMascotParams) (*DeleteMascotNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteMascotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteMascot",
		Method:             "DELETE",
		PathPattern:        "/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteMascotReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteMascotNoContent), nil

}

/*
GetMascot returns a mascot
*/
func (a *Client) GetMascot(params *GetMascotParams) (*GetMascotOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMascotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetMascot",
		Method:             "GET",
		PathPattern:        "/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMascotReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetMascotOK), nil

}

/*
UpdateMascot updates a mascot
*/
func (a *Client) UpdateMascot(params *UpdateMascotParams) (*UpdateMascotOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateMascotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "UpdateMascot",
		Method:             "PUT",
		PathPattern:        "/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateMascotReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UpdateMascotOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
