// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/billtrust/meetup-terraform-provider/api-client/models"
)

// NewUpdateMascotParams creates a new UpdateMascotParams object
// with the default values initialized.
func NewUpdateMascotParams() *UpdateMascotParams {
	var ()
	return &UpdateMascotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMascotParamsWithTimeout creates a new UpdateMascotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateMascotParamsWithTimeout(timeout time.Duration) *UpdateMascotParams {
	var ()
	return &UpdateMascotParams{

		timeout: timeout,
	}
}

// NewUpdateMascotParamsWithContext creates a new UpdateMascotParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateMascotParamsWithContext(ctx context.Context) *UpdateMascotParams {
	var ()
	return &UpdateMascotParams{

		Context: ctx,
	}
}

// NewUpdateMascotParamsWithHTTPClient creates a new UpdateMascotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateMascotParamsWithHTTPClient(client *http.Client) *UpdateMascotParams {
	var ()
	return &UpdateMascotParams{
		HTTPClient: client,
	}
}

/*UpdateMascotParams contains all the parameters to send to the API endpoint
for the update mascot operation typically these are written to a http.Request
*/
type UpdateMascotParams struct {

	/*ID*/
	ID string
	/*UpdateRequest*/
	UpdateRequest *models.UpdateMascotRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update mascot params
func (o *UpdateMascotParams) WithTimeout(timeout time.Duration) *UpdateMascotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update mascot params
func (o *UpdateMascotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update mascot params
func (o *UpdateMascotParams) WithContext(ctx context.Context) *UpdateMascotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update mascot params
func (o *UpdateMascotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update mascot params
func (o *UpdateMascotParams) WithHTTPClient(client *http.Client) *UpdateMascotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update mascot params
func (o *UpdateMascotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update mascot params
func (o *UpdateMascotParams) WithID(id string) *UpdateMascotParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update mascot params
func (o *UpdateMascotParams) SetID(id string) {
	o.ID = id
}

// WithUpdateRequest adds the updateRequest to the update mascot params
func (o *UpdateMascotParams) WithUpdateRequest(updateRequest *models.UpdateMascotRequest) *UpdateMascotParams {
	o.SetUpdateRequest(updateRequest)
	return o
}

// SetUpdateRequest adds the updateRequest to the update mascot params
func (o *UpdateMascotParams) SetUpdateRequest(updateRequest *models.UpdateMascotRequest) {
	o.UpdateRequest = updateRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMascotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.UpdateRequest != nil {
		if err := r.SetBodyParam(o.UpdateRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
