// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MascotResponse A Mascot.
// swagger:model MascotResponse
type MascotResponse struct {

	// returns the description
	// Read Only: true
	Description string `json:"description,omitempty"`

	// returns the id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// returns the name
	// Read Only: true
	Name string `json:"name,omitempty"`
}

// Validate validates this mascot response
func (m *MascotResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MascotResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MascotResponse) UnmarshalBinary(b []byte) error {
	var res MascotResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
